title: davigsilva blog
author:
  name: davigsilva
description:
  Blog para documentar meu aprendizado com desenvolvimento de software para web.
theme: minima
minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,   user_url: "https://github.com/davigsilva" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/davigsilva" }
  show_excerpts: true
header_pages:
  - about.md
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "base"
